-- Sample data for the mining operations dashboard.
-- The figures are synthetic and match the KPIs shown in the dashboard.
-- This is not the original project dataset or SQL.
--
-- Select a Snowflake database and warehouse before running:
--   USE DATABASE YOUR_DATABASE;
--   USE WAREHOUSE YOUR_WAREHOUSE;
--
-- Re-running the script replaces the tables and views below.

CREATE SCHEMA IF NOT EXISTS PORTFOLIO_MINING_BRONZE;
CREATE SCHEMA IF NOT EXISTS PORTFOLIO_MINING_SILVER;
CREATE SCHEMA IF NOT EXISTS PORTFOLIO_MINING_GOLD;

-- Bronze: source data

CREATE OR REPLACE TABLE PORTFOLIO_MINING_BRONZE.MONTHLY_PRODUCTION AS
SELECT
    TO_DATE(COLUMN1) AS MONTH_START,
    COLUMN2::NUMBER(14, 0) AS TONNES_PRODUCED,
    (COLUMN2 * 0.34)::NUMBER(14, 2) AS FUEL_LITRES
FROM VALUES
    ('2025-01-01', 2900000),
    ('2025-02-01', 2580000),
    ('2025-03-01', 2900000),
    ('2025-04-01', 2870000),
    ('2025-05-01', 2880000),
    ('2025-06-01', 2810000),
    ('2025-07-01', 2910000),
    ('2025-08-01', 2980000),
    ('2025-09-01', 2760000),
    ('2025-10-01', 2880000),
    ('2025-11-01', 2800000),
    ('2025-12-01', 2960000);

-- Monthly equipment hours and utilisation.
CREATE OR REPLACE TABLE PORTFOLIO_MINING_BRONZE.EQUIPMENT_MONTHLY AS
WITH EQUIPMENT_TYPES AS (
    SELECT
        COLUMN1::VARCHAR AS EQUIPMENT_TYPE,
        COLUMN2::NUMBER(5, 2) AS TARGET_UTILISATION_PCT
    FROM VALUES
        ('GRADER', 74.40),
        ('HAUL TRUCK', 74.30),
        ('DOZER', 74.20),
        ('DRILL', 74.10),
        ('LOADER', 74.00),
        ('EXCAVATOR', 73.90),
        ('WATER TRUCK', 73.80)
), NUMBERED AS (
    SELECT
        P.MONTH_START,
        E.EQUIPMENT_TYPE,
        E.TARGET_UTILISATION_PCT,
        ROW_NUMBER() OVER (
            ORDER BY P.MONTH_START, E.EQUIPMENT_TYPE
        ) AS ROW_NUM
    FROM PORTFOLIO_MINING_BRONZE.MONTHLY_PRODUCTION P
    CROSS JOIN EQUIPMENT_TYPES E
)
SELECT
    MONTH_START,
    EQUIPMENT_TYPE,
    (1230 + IFF(ROW_NUM <= 80, 1, 0))::NUMBER(10, 0) AS OPERATING_HOURS,
    ROUND(
        (1230 + IFF(ROW_NUM <= 80, 1, 0))
        / (TARGET_UTILISATION_PCT / 100.0),
        4
    )::NUMBER(12, 4) AS SCHEDULED_HOURS
FROM NUMBERED;

-- Work orders: 65 overdue, 25 open and 90 completed at 31 December 2025.
CREATE OR REPLACE TABLE PORTFOLIO_MINING_BRONZE.WORK_ORDERS AS
WITH NUMBERS AS (
    SELECT ROW_NUMBER() OVER (ORDER BY SEQ4()) AS ROW_NUM
    FROM TABLE(GENERATOR(ROWCOUNT => 180))
)
SELECT
    'WO-' || LPAD(ROW_NUM::VARCHAR, 4, '0') AS WORK_ORDER_ID,
    CASE MOD(ROW_NUM - 1, 7)
        WHEN 0 THEN 'GRADER'
        WHEN 1 THEN 'HAUL TRUCK'
        WHEN 2 THEN 'DOZER'
        WHEN 3 THEN 'DRILL'
        WHEN 4 THEN 'LOADER'
        WHEN 5 THEN 'EXCAVATOR'
        ELSE 'WATER TRUCK'
    END AS EQUIPMENT_TYPE,
    IFF(MOD(ROW_NUM, 3) = 0, 'Corrective', 'Preventive') AS WORK_ORDER_TYPE,
    CASE
        WHEN ROW_NUM <= 65
            THEN DATEADD(day, -(MOD(ROW_NUM, 60) + 1), DATE '2025-12-31')
        WHEN ROW_NUM <= 90
            THEN DATEADD(day, MOD(ROW_NUM, 30) + 1, DATE '2025-12-31')
        ELSE DATEADD(day, -(MOD(ROW_NUM, 90) + 10), DATE '2025-12-31')
    END::DATE AS DUE_DATE,
    CASE
        WHEN ROW_NUM > 90
            THEN DATEADD(day, -(MOD(ROW_NUM, 90) + 12), DATE '2025-12-31')
        ELSE NULL
    END::DATE AS COMPLETED_DATE
FROM NUMBERS;

-- Silver: cleaned data

CREATE OR REPLACE VIEW PORTFOLIO_MINING_SILVER.MONTHLY_PRODUCTION AS
SELECT
    MONTH_START,
    TONNES_PRODUCED,
    FUEL_LITRES,
    ROUND(FUEL_LITRES / NULLIF(TONNES_PRODUCED, 0), 4) AS FUEL_LITRES_PER_TONNE
FROM PORTFOLIO_MINING_BRONZE.MONTHLY_PRODUCTION
WHERE TONNES_PRODUCED > 0
  AND FUEL_LITRES >= 0;

CREATE OR REPLACE VIEW PORTFOLIO_MINING_SILVER.EQUIPMENT_MONTHLY AS
SELECT
    MONTH_START,
    INITCAP(TRIM(EQUIPMENT_TYPE)) AS EQUIPMENT_TYPE,
    OPERATING_HOURS,
    SCHEDULED_HOURS,
    ROUND(100.0 * OPERATING_HOURS / NULLIF(SCHEDULED_HOURS, 0), 2)
        AS UTILISATION_PCT
FROM PORTFOLIO_MINING_BRONZE.EQUIPMENT_MONTHLY
WHERE OPERATING_HOURS >= 0
  AND SCHEDULED_HOURS > 0
  AND OPERATING_HOURS <= SCHEDULED_HOURS;

CREATE OR REPLACE VIEW PORTFOLIO_MINING_SILVER.WORK_ORDERS AS
SELECT
    WORK_ORDER_ID,
    INITCAP(TRIM(EQUIPMENT_TYPE)) AS EQUIPMENT_TYPE,
    WORK_ORDER_TYPE,
    DUE_DATE,
    COMPLETED_DATE,
    DATE '2025-12-31' AS AS_OF_DATE,
    CASE
        WHEN COMPLETED_DATE IS NOT NULL THEN 'Completed'
        WHEN DUE_DATE < DATE '2025-12-31' THEN 'Overdue'
        ELSE 'Open'
    END AS WORK_ORDER_STATUS
FROM PORTFOLIO_MINING_BRONZE.WORK_ORDERS
WHERE WORK_ORDER_ID IS NOT NULL
  AND DUE_DATE IS NOT NULL;

-- Gold: views for Power BI

CREATE OR REPLACE VIEW PORTFOLIO_MINING_GOLD.MONTHLY_PRODUCTION AS
SELECT
    MONTH_START,
    SUM(TONNES_PRODUCED) AS TOTAL_TONNES,
    SUM(FUEL_LITRES) AS TOTAL_FUEL_LITRES,
    ROUND(SUM(FUEL_LITRES) / NULLIF(SUM(TONNES_PRODUCED), 0), 2)
        AS FUEL_LITRES_PER_TONNE
FROM PORTFOLIO_MINING_SILVER.MONTHLY_PRODUCTION
GROUP BY MONTH_START;

CREATE OR REPLACE VIEW PORTFOLIO_MINING_GOLD.EQUIPMENT_UTILISATION AS
SELECT
    EQUIPMENT_TYPE,
    SUM(OPERATING_HOURS) AS TOTAL_OPERATING_HOURS,
    ROUND(AVG(UTILISATION_PCT), 2) AS AVG_UTILISATION_PCT
FROM PORTFOLIO_MINING_SILVER.EQUIPMENT_MONTHLY
GROUP BY EQUIPMENT_TYPE;

CREATE OR REPLACE VIEW PORTFOLIO_MINING_GOLD.WORK_ORDER_STATUS AS
SELECT
    WORK_ORDER_STATUS,
    COUNT(*) AS WORK_ORDER_COUNT
FROM PORTFOLIO_MINING_SILVER.WORK_ORDERS
GROUP BY WORK_ORDER_STATUS;

CREATE OR REPLACE VIEW PORTFOLIO_MINING_GOLD.DASHBOARD_KPIS AS
SELECT
    P.TOTAL_TONNES,
    E.AVG_UTILISATION_PCT,
    E.TOTAL_OPERATING_HOURS,
    W.OVERDUE_WORK_ORDERS,
    ROUND(P.TOTAL_FUEL_LITRES / NULLIF(P.TOTAL_TONNES, 0), 2)
        AS FUEL_LITRES_PER_TONNE
FROM (
    SELECT
        SUM(TONNES_PRODUCED) AS TOTAL_TONNES,
        SUM(FUEL_LITRES) AS TOTAL_FUEL_LITRES
    FROM PORTFOLIO_MINING_SILVER.MONTHLY_PRODUCTION
) P
CROSS JOIN (
    SELECT
        ROUND(AVG(UTILISATION_PCT), 2) AS AVG_UTILISATION_PCT,
        SUM(OPERATING_HOURS) AS TOTAL_OPERATING_HOURS
    FROM PORTFOLIO_MINING_SILVER.EQUIPMENT_MONTHLY
) E
CROSS JOIN (
    SELECT COUNT_IF(WORK_ORDER_STATUS = 'Overdue') AS OVERDUE_WORK_ORDERS
    FROM PORTFOLIO_MINING_SILVER.WORK_ORDERS
) W;

-- Check that the totals match the dashboard. Each result should be TRUE.
SELECT
    TOTAL_TONNES = 34230000 AS TONNES_MATCH,
    AVG_UTILISATION_PCT = 74.10 AS UTILISATION_MATCH,
    TOTAL_OPERATING_HOURS = 103400 AS OPERATING_HOURS_MATCH,
    OVERDUE_WORK_ORDERS = 65 AS OVERDUE_WORK_ORDERS_MATCH,
    FUEL_LITRES_PER_TONNE = 0.34 AS FUEL_PER_TONNE_MATCH
FROM PORTFOLIO_MINING_GOLD.DASHBOARD_KPIS;

-- Power BI inputs.
SELECT * FROM PORTFOLIO_MINING_GOLD.DASHBOARD_KPIS;
SELECT * FROM PORTFOLIO_MINING_GOLD.MONTHLY_PRODUCTION ORDER BY MONTH_START;
SELECT * FROM PORTFOLIO_MINING_GOLD.EQUIPMENT_UTILISATION ORDER BY EQUIPMENT_TYPE;
SELECT * FROM PORTFOLIO_MINING_GOLD.WORK_ORDER_STATUS ORDER BY WORK_ORDER_STATUS;
